### ISSUE TITLE
[BUG] init command

### ISSUE THREAD

**Issue by jtqfaire** [adrien2p/medusa-extender#123]
Hi,

When i trying to launch the following command:

This error appears:

```bash
./node_modules/.bin/medex init
[MEDEX-CLI]      - 8/23/2022, 8:21:18 AM   [Init command] Initialising medusa-extender...
[MEDEX-CLI]      - 8/23/2022, 8:21:18 AM   [Init command] [Packages] Check that the packages are installed
[MEDEX-CLI]      - 8/23/2022, 8:21:18 AM   [Init command] Installing the necessary packages if they are not already installed
[MEDEX-CLI]      - 8/23/2022, 8:21:18 AM   [Init command] Installing typescript@4.5.5...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[MEDEX-CLI]      - 8/23/2022, 8:21:24 AM   [Init command] Installing nodemon@2.0.15...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[MEDEX-CLI]      - 8/23/2022, 8:21:33 AM   [Init command] Installing ts-node@10.7.0...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[MEDEX-CLI]      - 8/23/2022, 8:21:38 AM   [Init command] Packages installed
[MEDEX-CLI]      - 8/23/2022, 8:21:38 AM   [Init command] [Scripts] Update package.json scripts
[MEDEX-CLI]      - 8/23/2022, 8:21:38 AM   [Init command] [TsConfig] Create or update tsconfig.json
[MEDEX-CLI]      - 8/23/2022, 8:21:38 AM   [Init command] [tsconfig.json] Update tsconfig.json
(node:129438) UnhandledPromiseRejectionWarning: SyntaxError: /home/kereval.com/bcu/perso/lrvlb/la-ruee-vers-le-bois-store/tsconfig.json: Unexpected token } in JSON at position 65
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1128:22)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at /home/kereval.com/bcu/perso/lrvlb/la-ruee-vers-le-bois-store/node_modules/medusa-extender/dist/cli/commands/init.js:84:61
    at async updateTsconfigJson (/home/kereval.com/bcu/perso/lrvlb/la-ruee-vers-le-bois-store/node_modules/medusa-extender/dist/cli/commands/init.js:84:26)
    at async init (/home/kereval.com/bcu/perso/lrvlb/la-ruee-vers-le-bois-store/node_modules/medusa-extender/dist/cli/commands/init.js:23:5)
    at async Command.<anonymous> (/home/kereval.com/bcu/perso/lrvlb/la-ruee-vers-le-bois-store/node_modules/medusa-extender/dist/cli/index.js:65:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:129438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:129438) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Remove the `,` in `tsconfig.json` solved the problem

**Comment by adrien2p** [comment]
Could you give me a bit more info please? 

After which property the comma was? Does the tsconfig was already existing ?

**Comment by jtqfaire** [comment]
Hi,

The tsconfig file:

```
{
  "compilerOptions": {
    "experimentalDecorators": true
  },
}
```

Update to this solved the problem on my side:

```
{
  "compilerOptions": {
    "experimentalDecorators": true
  }
}

```

**Comment by adrien2p** [comment]
When you ran the init command, the tsconfig did not contains an include/exclude properties?

**Comment by adrien2p** [comment]
@jtqfaire have you seen my previous message ?
