### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by swarmlab-hybrid** [adrien2p/medusa-extender#48]
Failed to build

**To Reproduce**
npx degit github:adrien2p/medusa-extender/starters/server#main server
cd server
npm i
npm run build
npm run start

Initializing databasenode:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: getaddrinfo ENOTFOUND undefined
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined'
}

**Comment by adrien2p** [comment]
Hello there, could you please add an understandable title please that describe quickly the bug 🙏

**Comment by adrien2p** [comment]
Did you update your `medusa-config` file accordingly yo your needs?

**Comment by swarmlab-hybrid** [comment]
fresh install from here https://github.com/medusajs/docker-medusa-temp

**Comment by adrien2p** [comment]
If you cloned that repo, you should follow the getting started from an existing project not from the starter. Unless it was what you want? In both case, update your env file and configure your medusa-config.js file before running the backend

**Comment by swarmlab-hybrid** [comment]
I closed everything that worked from that repo (https://github.com/medusajs/docker-medusa-temp) , except redis  and tried to build  it again. now i get this error:
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}

**Comment by adrien2p** [comment]
Could you show your config-medusa.js file please

**Comment by swarmlab-hybrid** [comment]
Yes i now - I tried it also

here is my config file

import * as dotenv from 'dotenv';

let ENV_FILE_NAME = '';
switch (process.env.NODE_ENV) {
	case 'prod':
		ENV_FILE_NAME = '.env';
		break;
	case 'test':
		ENV_FILE_NAME = '.env.test';
		break;
	default:
		ENV_FILE_NAME = '.env';
		break;
}

dotenv.config({ path: process.cwd() + '/' + ENV_FILE_NAME });

// Try 1
//const REDIS_URL = process.env.REDIS_URL || 'redis://localhost:6379';
const REDIS_URL = process.env.REDIS_URL || '';
const PORT = process.env.PORT || 3000;
const ADMIN_CORS = process.env.ADMIN_CORS || '';
const STORE_CORS = process.env.STORE_CORS || '';

// Try 2
//const ADMIN_CORS = process.env.ADMIN_CORS || "http://localhost:7000";
//const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";
//const DATABASE_URL =
//  process.env.DATABASE_URL || "postgres://localhost/medusa-store";
//const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

// Stripe keys
const STRIPE_API_KEY = process.env.STRIPE_API_KEY || "";
const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET || "";

const plugins = [
	`medusa-fulfillment-manual`,
	`medusa-payment-manual`,
];

module.exports = {
	serverConfig: {
		port: PORT,
	},
	projectConfig: {
		// redis_url: REDIS_URL,
		// For more production-like environment install PostgresQL
		jwtSecret: process.env.JWT_SECRET,
		cookieSecret: process.env.COOKIE_SECRET,
		database_url: `postgres://${process.env.DB_USERNAME}:${process.env.DB_PASSWORD}@${process.env.DB_HOST}:${process.env.DB_PORT}/medusa`,
    //database_url: DATABASE_URL,
		database_type: 'postgres',
		store_cors: STORE_CORS,
		admin_cors: ADMIN_CORS,
		redis_url: REDIS_URL,
	},
	monitoring: {
        uriPath: '/monitoring'
    },
	plugins,
};

**Comment by adrien2p** [comment]
Ok, did you fill your env file?

**Comment by swarmlab-hybrid** [comment]
i try it localy.

I have run it with the following but also with empty valiables

```
PORT=3000
DB_HOST=localhost
DB_PORT=localhost
DB_USERNAME=
DB_PASSWORD=
DB_DATABASE=
JWT_SECRET=test
JWT_EXPIRESIN=
COOKIE_SECRET=test
REDIS_URL=localhost
REDIS_URI=
ADMIN_CORS=
STORE_CORS=
```

**Comment by adrien2p** [comment]
already I can see some mistakes in your env

`DB_PORT` is set to `localhost` but should probably be `5432` or the port you've chosen 
`DB_USERNAME` is empty, should not be empty
`DB_PASSWORD` is empty, should not be empty

Could you update your env and then build and re run your local server?

**Comment by swarmlab-hybrid** [comment]
I have some progress
**1.** create database medusa 
**2.** user and secret
```javascript
PORT=3000
DB_HOST=localhost
DB_PORT=5432
DB_USERNAME=
```
on build i have this error
```sh
Error: Services must inherit from BaseService, please check /node_modules/medusa-fulfillment-manual/services/manual-fulfillment.js
    at /data/appl/ok/gitversion/swarmlab-olivenkiste/medusa-extender/starters/server/node_modules/medusa-extender/node_modules/@medusajs/medusa/dist/loaders/plugins.js:312:51
    at step (/data/appl/ok/gitversion/swarmlab-olivenkiste/medusa-extender/starters/server/node_modules/medusa-extender/node_modules/@medusajs/medusa/dist/loaders/plugins.js:33:23)
    at Object.next (/data/appl/ok/gitversion/swarmlab-olivenkiste/medusa-extender/starters/server/node_modules/medusa-extender/node_modules/@medusajs/medusa/dist/loaders/plugins.js:14:53)
    at /data/appl/ok/gitversion/swarmlab-olivenkiste/medusa-extender/starters/server/node_modules/medusa-extender/node_modules/@medusajs/medusa/dist/loaders/plugins.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/data/appl/ok/gitversion/swarmlab-olivenkiste/medusa-extender/starters/server/node_modules/medusa-extender/node_modules/@medusajs/medusa/dist/loaders/plugins.js:4:12)
    at /data/appl/ok/gitversion/swarmlab-olivenkiste/medusa-extender/starters/server/node_modules/medusa-extender/node_modules/@medusajs/medusa/dist/loaders/plugins.js:300:87
    at Array.map (<anonymous>)
    at /data/appl/ok/gitversion/swarmlab-olivenkiste/medusa-extender/starters/server/node_modules/medusa-extender/node_modules/@medusajs/medusa/dist/loaders/plugins.js:300:60
    at step (/data/appl/ok/gitversion/swarmlab-olivenkiste/medusa-extender/starters/server/node_modules/medusa-extender/node_modules/@medusajs/medusa/dist/loaders/plugins.js:33:23)
```

**Comment by adrien2p** [comment]
Hey 👋 it is 5am here now 🤣

It seams that the package.json form the docker repo has not been updated. Could you update the version of all medusa related packages to the latest.

**Comment by swarmlab-hybrid** [comment]
I finally installed it following
https://medium.com/medusa-commerce/create-a-marketplace-using-medusa-part-1-6bb3e876e5db
( it is 14:30 GMT+2,  not bad :-)  )

**Comment by adrien2p** [comment]
Perfect 🤩 so we are in the same TZ

**Comment by adrien2p** [comment]
Also the marketplace tutorial is based on the server starter 👍
