### ISSUE TITLE
[BUG] Conflicting migration names with using .migration.ts

### ISSUE THREAD

**Issue by dwene** [adrien2p/medusa-extender#92]
**Describe the bug**
I create a migration with the normal structure of `modules/:module_name/migrations/:module_name.migration.ts`, annotate it with @Migration, and import it into the module. When I try to run `medex migrate --run`, it fails with a duplicate migration detected error

**To Reproduce**
Create a migration in a module, and name it `anything-you-want.migration.ts`
Create the migration following medusa-extender documentation.
`yarn build` into a `dist` folder to compile typescript to javascript.
try running `medex migrate --run`. Notice you will get an error like this:

```
UnhandledPromiseRejectionWarning: Error: Duplicate migrations: addIsRecurringToDiscount1651767613018
    at MigrationExecutor.checkForDuplicateMigrations (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/typeorm/migration/MigrationExecutor.js:546:19)
    at MigrationExecutor.getMigrations (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/typeorm/migration/MigrationExecutor.js:538:14)
    at MigrationExecutor.<anonymous> (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/typeorm/migration/MigrationExecutor.js:220:46)
    at step (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/derekwene/src/nibll/nibll-home/apps/home/api-medusa/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

**Expected behavior**
The migrations are run without error

**Screenshots**
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/12628251/169918406-908a98f7-3e59-4210-8bb7-37ddae895375.png">

**Workaround:**
Now change the name of your migration file to `anything-you-want-migration.ts`. Compile the typescript and notice it runs the migration fine now.

**Package version:**
 - Version 1.7.0

**Additional context**

**Comment by adrien2p** [comment]
Humm, I don't see why since the file name and name contains both the timestamp which avoid conflicting with other files. I will try to reproduce with you step and let you know

**Comment by adrien2p** [comment]
yeah, but the migrations can go anywhere as long as they are decorated, but when there is an error such as the one you mentioned, it means that there is twice the same migration, which is weird

**Comment by adrien2p** [comment]
will be resolve in the next release
